package com.ovvium.services.security.exception;

public enum AccountError {
	INVALID_USER, INVALID_PASSWORD, EXPIRED_TOKEN, INVALID_TOKEN, USER_ALREADY_USED, INACTIVE_USER, AUTHENTICATION_CODE_INVALID, TOKEN_NOT_PRESENT, SOCIAL_LOGIN_ERROR, ACTIVATION_CODE_INVALID
}