package com.ovvium.services.util.util.client;

public enum OnNotFound {

    /**
     * Returns null value
     */
    NULL,

    /**
     * Returns "empty" response, generated by ApiClient
     */
    EMPTY,

    /**
     * Throws a ClientException
     */
    EXCEPTION,

    /**
     * Constructs default response, just like 2xx status
     */
    OK
}
